title: Paulis RÃ¸dder
description: "Vi har ingen kaptajn"
baseurl: ""
url: "https://paulisrodder.github.io"

# Build settings
markdown: kramdown
theme: minima

collections:
  klubsange:
    output: true
    permalink: /klubsange/:name/
  spillersange_nuvaerende:
    output: true
    permalink: /spillersange/nuvaerende/:name/
  spillersange_tidligere:
    output: true
    permalink: /spillersange/tidligere/:name/

exclude:
  - docs
