title: Paulis RÃ¸dder
description: "Vi har ingen kaptajn"
baseurl: ""
url: "https://paulisrodder.github.io"

# Build settings
markdown: kramdown
theme: minima

collections:
  songs:
    output: true
    permalink: /songs/:name/